### PR TITLE
Fixed Tanglekit TKIf and TKSwitch classes' element display behavior

### PR DESCRIPTION
**Pull request by edgerunner**
When `TKIf` and `TKSwitch` would hide and show elements, they put the `display: none` property on them but reverted to `display: inline` regardless of what the element was.

Now it just removes the element style property so that the element reverts to its natural display state rather than being forced into `inline`

Hope it helps

### CODE REVIEW

**Comment by worrydream** [comment]
Thanks!

**Comment by edgerunner** [comment]
You're welcome Bret. 

Is there a reason you manually put in the changes instead of merging?

**Comment by worrydream** [comment]
Just a spaces vs tabs problem with the patch.  (And unfamiliarity with the "right" way to correct that with git.)

**Comment by edgerunner** [comment]
:D Never thought of that. I should have. (Technically it is Merge > Fix tabs > commit)

**Pull request closed without merging**
